"""empty message

Revision ID: 469322a02519
Revises: e84c2a408d4f
Create Date: 2020-03-25 16:58:13.204760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '469322a02519'
down_revision = 'e84c2a408d4f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_info',
    sa.Column('device_id', sa.Integer(), nullable=False),
    sa.Column('motor_room', sa.String(length=32), nullable=False),
    sa.Column('rack', sa.String(length=32), nullable=False),
    sa.Column('device_name', sa.String(length=32), nullable=False),
    sa.Column('operation', sa.String(length=32), nullable=False),
    sa.Column('buy_time', sa.String(length=32), nullable=False),
    sa.Column('over_time', sa.String(length=32), nullable=False),
    sa.Column('detail', sa.String(length=1024), nullable=False),
    sa.PrimaryKeyConstraint('device_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('device_info')
    # ### end Alembic commands ###
