"""empty message

Revision ID: 61fc00492004
Revises: 469322a02519
Create Date: 2020-04-10 12:34:16.673300

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '61fc00492004'
down_revision = '469322a02519'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('system',
    sa.Column('CPU_LOAD', sa.String(length=32), nullable=False),
    sa.Column('DISK', sa.String(length=32), nullable=True),
    sa.Column('USED', sa.String(length=32), nullable=True),
    sa.Column('FREE', sa.String(length=32), nullable=True),
    sa.PrimaryKeyConstraint('CPU_LOAD')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('system')
    # ### end Alembic commands ###
