"""empty message

Revision ID: 9e4a1bd9ea3a
Revises: c891b1c9835d
Create Date: 2020-04-21 15:09:12.378504

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9e4a1bd9ea3a'
down_revision = 'c891b1c9835d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('images',
    sa.Column('image_id', sa.String(length=108), nullable=False),
    sa.Column('repository', sa.String(length=108), nullable=True),
    sa.Column('tage', sa.String(length=108), nullable=True),
    sa.PrimaryKeyConstraint('image_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('images')
    # ### end Alembic commands ###
