"""empty message

Revision ID: c891b1c9835d
Revises: 226347ec4bb2
Create Date: 2020-04-21 11:42:40.881751

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c891b1c9835d'
down_revision = '226347ec4bb2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pod',
    sa.Column('pod_name', sa.String(length=108), nullable=False),
    sa.Column('pod_namespace', sa.String(length=108), nullable=True),
    sa.Column('pod_ip', sa.String(length=64), nullable=True),
    sa.Column('pod_image', sa.String(length=108), nullable=True),
    sa.PrimaryKeyConstraint('pod_name')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pod')
    # ### end Alembic commands ###
