"""empty message

Revision ID: e84c2a408d4f
Revises: 
Create Date: 2020-03-10 15:25:28.079868

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e84c2a408d4f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('build_info',
    sa.Column('jenkins_id', sa.Integer(), nullable=False),
    sa.Column('jenkins_name', sa.String(length=32), nullable=False),
    sa.Column('consul_url', sa.String(length=1024), nullable=False),
    sa.Column('start_time', sa.String(length=32), nullable=False),
    sa.Column('result', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('jenkins_id'),
    sa.UniqueConstraint('consul_url')
    )
    op.create_table('kube_info',
    sa.Column('kube_id', sa.Integer(), nullable=False),
    sa.Column('environment', sa.String(length=32), nullable=False),
    sa.Column('service_name', sa.String(length=1024), nullable=False),
    sa.Column('service_start_time', sa.String(length=32), nullable=False),
    sa.Column('git_addr', sa.String(length=32), nullable=False),
    sa.PrimaryKeyConstraint('kube_id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=32), nullable=False),
    sa.Column('password', sa.String(length=128), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('kube_info')
    op.drop_table('build_info')
    # ### end Alembic commands ###
